# HTTPS server configuration
server.port=8443

# SSL certificate settings
server.ssl.key-alias=selfsigned
server.ssl.key-store-password=1011136
server.ssl.key-store-type=PKCS12
server.ssl.key-store=file:keystore.p12
